/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
(function(){function y(a){function b(){this.deflated||(a.widgets.focused==this.widget&&(this.focused=!0),a.widgets.destroy(this.widget),this.deflated=!0)}function g(){var b=a.editable(),c=a.document;if(this.deflated)this.widget=a.widgets.initOn(this.element,"image",this.widget.data),this.widget.inline&&!(new CKEDITOR.dom.elementPath(this.widget.wrapper,b)).block&&(b=c.createElement(a.activeEnterMode==CKEDITOR.ENTER_P?"p":"div"),b.replace(this.widget.wrapper),this.widget.wrapper.move(b)),this.focused&&
(this.widget.focus(),delete this.focused),delete this.deflated;else{var d=this.widget,b=e,c=d.wrapper,f=d.data.align,d=d.data.hasCaption;if(b){for(var j=3;j--;)c.removeClass(b[j]);"center"==f?d&&c.addClass(b[1]):"none"!=f&&c.addClass(b[m[f]])}else"center"==f?(d?c.setStyle("text-align","center"):c.removeStyle("text-align"),c.removeStyle("float")):("none"==f?c.removeStyle("float"):c.setStyle("float",f),c.removeStyle("text-align"))}}var e=a.config.image2_alignClasses,f=a.config.image2_captionedClass;
return{allowedContent:z(a),requiredContent:"img[src,alt]",features:A(a),styleableElements:"img figure",contentTransformations:[["img[width]: sizeToAttribute"]],editables:{caption:{selector:"figcaption",allowedContent:"br em strong sub sup u s; a[!href]"}},parts:{image:"img",caption:"figcaption"},dialog:"image2",template:t,data:function(){var e=this.features;this.data.hasCaption&&!a.filter.checkFeature(e.caption)&&(this.data.hasCaption=!1);"none"!=this.data.align&&!a.filter.checkFeature(e.align)&&
(this.data.align="none");this.shiftState({widget:this,element:this.element,oldData:this.oldData,newData:this.data,deflate:b,inflate:g});this.data.link?this.parts.link||(this.parts.link=this.parts.image.getParent()):this.parts.link&&(this.parts.link=null);this.parts.image.setAttributes({src:this.data.src,"data-cke-saved-src":this.data.src,alt:this.data.alt});if(this.oldData&&!this.oldData.hasCaption&&this.data.hasCaption)for(var c in this.data.classes)this.parts.image.removeClass(c);if(a.filter.checkFeature(e.dimension)){e=
this.data;e={width:e.width,height:e.height};c=this.parts.image;for(var d in e)e[d]?c.setAttribute(d,e[d]):c.removeAttribute(d)}this.oldData=CKEDITOR.tools.extend({},this.data)},init:function(){var b=CKEDITOR.plugins.image2,c=this.parts.image,d={hasCaption:!!this.parts.caption,src:c.getAttribute("src"),alt:c.getAttribute("alt")||"",width:c.getAttribute("width")||"",height:c.getAttribute("height")||"",lock:this.ready?b.checkHasNaturalRatio(c):!0};this.parts.link=this.element.is("a")?this.element:this.element.getFirst(function(a){return a.is("a")});
d.align||(e?(this.element.hasClass(e[0])?d.align="left":this.element.hasClass(e[2])&&(d.align="right"),d.align?this.element.removeClass(e[m[d.align]]):d.align="none"):(d.align=this.element.getStyle("float")||c.getStyle("float")||"none",this.element.removeStyle("float"),c.removeStyle("float")));if(a.plugins.link&&this.parts.link&&(d.link=CKEDITOR.plugins.link.parseLinkAttributes(a,this.parts.link),(c=d.link.advanced)&&c.advCSSClasses))c.advCSSClasses=CKEDITOR.tools.trim(c.advCSSClasses.replace(/cke_\S+/,
""));this.wrapper[(d.hasCaption?"remove":"add")+"Class"]("cke_image_nocaption");this.setData(d);a.filter.checkFeature(this.features.dimension)&&B(this);this.shiftState=b.stateShifter(this.editor);this.on("contextMenu",function(a){a.data.image=CKEDITOR.TRISTATE_OFF;a.data.link=CKEDITOR.TRISTATE_OFF;a.data.unlink=this.parts.link?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED});this.on("dialog",function(a){a.data.widget=this},this)},addClass:function(a){n(this).addClass(a)},hasClass:function(a){return n(this).hasClass(a)},
removeClass:function(a){n(this).removeClass(a)},getClasses:function(){var a=RegExp("^("+[].concat(f,e).join("|")+")$");return function(){var b=this.repository.parseElementClasses(n(this).getAttribute("class")),e;for(e in b)a.test(e)&&delete b[e];return b}}(),upcast:C(a),downcast:D(a)}}function C(a){var b=o(a),g=a.config.image2_captionedClass;return function(a,f){var h={width:1,height:1},c=a.name,d;if(!a.attributes["data-cke-realelement"]){if(b(a)){if("div"==c&&(d=a.getFirst("figure")))a.replaceWith(d),
a=d;f.align="center";d=a.getFirst("img")||a.getFirst("a").getFirst("img")}else"figure"==c&&a.hasClass(g)?d=a.getFirst("img")||a.getFirst("a").getFirst("img"):k(a)&&(d="a"==a.name?a.children[0]:a);if(d){for(var i in h)(c=d.attributes[i])&&c.match(E)&&delete d.attributes[i];return a}}}}function D(a){var b=a.config.image2_alignClasses;return function(a){var e="a"==a.name?a.getFirst():a,f=e.attributes,h=this.data.align;if(!this.inline){var c=a.getFirst("span");c&&c.replaceWith(c.getFirst({img:1,a:1}))}h&&
"none"!=h&&(c=CKEDITOR.tools.parseCssText(f.style||""),"center"==h&&"figure"==a.name?a=a.wrapWith(new CKEDITOR.htmlParser.element("div",b?{"class":b[1]}:{style:"text-align:center"})):h in{left:1,right:1}&&(b?e.addClass(b[m[h]]):c["float"]=h),!b&&!CKEDITOR.tools.isEmpty(c)&&(f.style=CKEDITOR.tools.writeCssText(c)));return a}}function o(a){var b=a.config.image2_captionedClass,g=a.config.image2_alignClasses,e={figure:1,a:1,img:1};return function(f){if(!(f.name in{div:1,p:1}))return!1;var h=f.children;
if(1!==h.length)return!1;h=h[0];if(!(h.name in e))return!1;if("p"==f.name){if(!k(h))return!1}else if("figure"==h.name){if(!h.hasClass(b))return!1}else if(a.enterMode==CKEDITOR.ENTER_P||!k(h))return!1;return(g?f.hasClass(g[1]):"center"==CKEDITOR.tools.parseCssText(f.attributes.style||"",!0)["text-align"])?!0:!1}}function k(a){return"img"==a.name?!0:"a"==a.name?1==a.children.length&&a.getFirst("img"):!1}function B(a){var b=a.editor,g=b.editable(),e=b.document,f=a.resizer=e.createElement("span");f.addClass("cke_image_resizer");
f.setAttribute("title",b.lang.image2.resizer);f.append(new CKEDITOR.dom.text("​",e));if(a.inline)a.wrapper.append(f);else{var h=a.parts.link||a.parts.image,c=h.getParent(),d=e.createElement("span");d.addClass("cke_image_resizer_wrapper");d.append(h);d.append(f);a.element.append(d,!0);c.is("span")&&c.remove()}f.on("mousedown",function(c){function j(a,b,c){var j=CKEDITOR.document,d=[];e.equals(j)||d.push(j.on(a,b));d.push(e.on(a,b));if(c)for(a=d.length;a--;)c.push(d.pop())}function d(){p=m+i*u;q=Math.round(p/
r)}function s(){q=o-l;p=Math.round(q*r)}var h=a.parts.image,i="right"==a.data.align?-1:1,n=c.data.$.screenX,F=c.data.$.screenY,m=h.$.clientWidth,o=h.$.clientHeight,r=m/o,k=[],t="cke_image_s"+(!~i?"w":"e"),x,p,q,w,u,l,v;b.fire("saveSnapshot");j("mousemove",function(a){x=a.data.$;u=x.screenX-n;l=F-x.screenY;v=Math.abs(u/l);1==i?0>=u?0>=l?d():v>=r?d():s():0>=l?v>=r?s():d():s():0>=u?0>=l?v>=r?s():d():s():0>=l?d():v>=r?d():s();15<=p&&15<=q?(h.setAttributes({width:p,height:q}),w=!0):w=!1},k);j("mouseup",
function(){for(var c;c=k.pop();)c.removeListener();g.removeClass(t);f.removeClass("cke_image_resizing");w&&(a.setData({width:p,height:q}),b.fire("saveSnapshot"));w=!1},k);g.addClass(t);f.addClass("cke_image_resizing")});a.on("data",function(){f["right"==a.data.align?"addClass":"removeClass"]("cke_image_resizer_left")})}function G(a){var b=[],g;return function(e){var f=a.getCommand("justify"+e);if(f){b.push(function(){f.refresh(a,a.elementPath())});if(e in{right:1,left:1,center:1})f.on("exec",function(f){var c=
i(a);if(c){c.setData("align",e);for(c=b.length;c--;)b[c]();f.cancel()}});f.on("refresh",function(b){var c=i(a),d={right:1,left:1,center:1};c&&(void 0==g&&(g=a.filter.checkFeature(a.widgets.registered.image.features.align)),g?this.setState(c.data.align==e?CKEDITOR.TRISTATE_ON:e in d?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED):this.setState(CKEDITOR.TRISTATE_DISABLED),b.cancel())})}}}function H(a){a.plugins.link&&(a.on("doubleclick",function(b){b.data.dialog&&("link"==b.data.dialog&&i(a))&&b.cancel()}),
CKEDITOR.on("dialogDefinition",function(b){b=b.data;if("link"==b.name){var b=b.definition,g=b.onShow,e=b.onOk;b.onShow=function(){var b=i(a);b&&(b.inline?!b.wrapper.getAscendant("a"):1)?this.setupContent(b.data.link||{}):g.apply(this,arguments)};b.onOk=function(){var b=i(a);if(b&&(b.inline?!b.wrapper.getAscendant("a"):1)){var g={};this.commitContent(g);b.setData("link",g)}else e.apply(this,arguments)}}}),a.getCommand("unlink").on("exec",function(b){var g=i(a);g&&(g.setData("link",null),this.refresh(a,
a.elementPath()),b.cancel())}),a.getCommand("unlink").on("refresh",function(b){var g=i(a);g&&(this.setState(g.data.link?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED),b.cancel())}))}function i(a){return(a=a.widgets.focused)&&"image"==a.name?a:null}function z(a){var b=a.config.image2_alignClasses,a={div:{match:o(a)},p:{match:o(a)},img:{attributes:"!src,alt,width,height"},figure:{classes:"!"+a.config.image2_captionedClass},figcaption:!0};b?(a.div.classes=b[1],a.p.classes=a.div.classes,a.img.classes=
b[0]+","+b[2],a.figure.classes+=","+a.img.classes):(a.div.styles="text-align",a.p.styles="text-align",a.img.styles="float",a.figure.styles="float,display");return a}function A(a){a=a.config.image2_alignClasses;return{dimension:{requiredContent:"img[width,height]"},align:{requiredContent:"img"+(a?"("+a[0]+")":"{float}")},caption:{requiredContent:"figcaption"}}}function n(a){return a.data.hasCaption?a.element:a.parts.image}var t='<img alt="" src="" />',I=new CKEDITOR.template('<figure class="{captionedClass}">'+
t+"<figcaption>{captionPlaceholder}</figcaption></figure>"),m={left:0,center:1,right:2},E=/^\s*(\d+\%)\s*$/i;CKEDITOR.plugins.add("image2",{lang:"af,ar,bg,bn,bs,ca,cs,cy,da,de,el,en,en-au,en-ca,en-gb,eo,es,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,tt,ug,uk,vi,zh,zh-cn",requires:"widget,dialog",icons:"image",hidpi:!0,onLoad:function(){CKEDITOR.addCss(".cke_image_nocaption{line-height:0}.cke_editable.cke_image_sw, .cke_editable.cke_image_sw *{cursor:sw-resize !important}.cke_editable.cke_image_se, .cke_editable.cke_image_se *{cursor:se-resize !important}.cke_image_resizer{display:none;position:absolute;width:10px;height:10px;bottom:-5px;right:-5px;background:#000;outline:1px solid #fff;line-height:0;cursor:se-resize;}.cke_image_resizer_wrapper{position:relative;display:inline-block;line-height:0;}.cke_image_resizer.cke_image_resizer_left{right:auto;left:-5px;cursor:sw-resize;}.cke_widget_wrapper:hover .cke_image_resizer,.cke_image_resizer.cke_image_resizing{display:block}.cke_widget_wrapper>a{display:inline-block}")},
init:function(a){var b=a.config,g=a.lang.image2,e=y(a);b.filebrowserImage2BrowseUrl=b.filebrowserImageBrowseUrl;b.filebrowserImage2UploadUrl=b.filebrowserImageUploadUrl;e.pathName=g.pathName;e.editables.caption.pathName=g.pathNameCaption;a.widgets.add("image",e);a.ui.addButton&&a.ui.addButton("Image",{label:a.lang.common.image,command:"image",toolbar:"insert,10"});a.contextMenu&&(a.addMenuGroup("image",10),a.addMenuItem("image",{label:g.menu,command:"image",group:"image"}));CKEDITOR.dialog.add("image2",
this.path+"dialogs/image2.js")},afterInit:function(a){var b={left:1,right:1,center:1,block:1},g=G(a),e;for(e in b)g(e);H(a)}});CKEDITOR.plugins.image2={stateShifter:function(a){function b(a,b){var c={};f?c.attributes={"class":f[1]}:c.styles={"text-align":"center"};c=e.createElement(a.activeEnterMode==CKEDITOR.ENTER_P?"p":"div",c);g(c,b);b.move(c);return c}function g(b,d){if(d.getParent()){var e=a.createRange();e.moveToPosition(d,CKEDITOR.POSITION_BEFORE_START);d.remove();c.insertElementIntoRange(b,
e)}else b.replace(d)}var e=a.document,f=a.config.image2_alignClasses,h=a.config.image2_captionedClass,c=a.editable(),d=["hasCaption","align","link"],i={align:function(c,d,e){var g=c.element;if(c.changed.align){if(!c.newData.hasCaption&&("center"==e&&(c.deflate(),c.element=b(a,g)),!c.changed.hasCaption&&"center"==d&&"center"!=e))c.deflate(),d=g.findOne("a,img"),d.replace(g),c.element=d}else"center"==e&&(c.changed.hasCaption&&!c.newData.hasCaption)&&(c.deflate(),c.element=b(a,g));!f&&g.is("figure")&&
("center"==e?g.setStyle("display","inline-block"):g.removeStyle("display"))},hasCaption:function(b,c,d){b.changed.hasCaption&&(c=b.element.is({img:1,a:1})?b.element:b.element.findOne("a,img"),b.deflate(),d?(d=CKEDITOR.dom.element.createFromHtml(I.output({captionedClass:h,captionPlaceholder:a.lang.image2.captionPlaceholder}),e),g(d,b.element),c.replace(d.findOne("img")),b.element=d):(c.replace(b.element),b.element=c))},link:function(b,c,d){if(b.changed.link){var g=b.element.is("img")?b.element:b.element.findOne("img"),
f=b.element.is("a")?b.element:b.element.findOne("a"),h=b.element.is("a")&&!d||b.element.is("img")&&d,i;h&&b.deflate();d?(c||(i=e.createElement("a",{attributes:{href:b.newData.link.url}}),i.replace(g),g.move(i)),d=CKEDITOR.plugins.link.getLinkAttributes(a,d),CKEDITOR.tools.isEmpty(d.set)||(i||f).setAttributes(d.set),d.removed.length&&(i||f).removeAttributes(d.removed)):(d=f.findOne("img"),d.replace(f),i=d);h&&(b.element=i)}}};return function(a){var b,c;a.changed={};for(c=0;c<d.length;c++)b=d[c],a.changed[b]=
a.oldData?a.oldData[b]!==a.newData[b]:!1;for(c=0;c<d.length;c++)b=d[c],i[b](a,a.oldData?a.oldData[b]:null,a.newData[b]);a.inflate()}},checkHasNaturalRatio:function(a){var b=a.$,a=this.getNatural(a);return Math.round(b.clientWidth/a.width*a.height)==b.clientHeight||Math.round(b.clientHeight/a.height*a.width)==b.clientWidth},getNatural:function(a){if(a.$.naturalWidth)a={width:a.$.naturalWidth,height:a.$.naturalHeight};else{var b=new Image;b.src=a.getAttribute("src");a={width:b.width,height:b.height}}return a}}})();
CKEDITOR.config.image2_captionedClass="image";